In [1]:
import pandas as pd
import numpy as np
from tqdm import tqdm
from sklearn.metrics import brier_score_loss, make_scorer, log_loss
from sklearn.model_selection import train_test_split, GridSearchCV, StratifiedKFold
from sklearn.compose import ColumnTransformer
from sklearn.impute import KNNImputer
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier

## Have to convert our target variable "target" to predicted probabilities using Logistic Regression

In [2]:
df = pd.read_csv("../Data/cleanedHealthData.csv")

In [3]:
df['target'].value_counts(normalize=True)

target
healthy     0.70097
diseased    0.29903
Name: proportion, dtype: float64

In [4]:
## Set target as 1|0

df['target'] = df['target'].replace({'healthy': 0, 'diseased': 1})

y = df['target']
X = df.drop(columns='target')

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

C:\Users\admin\AppData\Local\Temp\ipykernel_9548\3429725909.py:3: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['target'] = df['target'].replace({'healthy': 0, 'diseased': 1})

In [5]:
## Separate all the columns
numerical_cols = df.select_dtypes(include=['number']).columns
categorical_cols = list(df.select_dtypes(exclude=['number']).columns)
numerical_cols = [col for col in numerical_cols if col != 'target']

In [6]:
## Setup Numerical and Categorical Cols Transformers (KNNImputer, Scaler and OHE)

num_transformer = Pipeline([
    ('imputer', KNNImputer(n_neighbors=5)),
    ('scaler', StandardScaler()),
])

cat_transformer = Pipeline([
    ('ohe', OneHotEncoder(drop = 'first', handle_unknown='ignore'))
])

preprocessor = ColumnTransformer(
    transformers = [
        ('num', num_transformer, numerical_cols),
        ('cat', cat_transformer, categorical_cols)
    ]
)

## Logistic Regression Model

In [ ]:
## Logistic Regression pipeline (0.37087518762791943)

pipeline = Pipeline(steps=[
    ('preprocessor', preprocessor),
    ('classifier', LogisticRegression(random_state=42))
])

pipeline.fit(X_train, y_train)

## Predict

y_pred_prob = pipeline.predict_proba(X_test)[:,1]

## Brier Score Loss
brier = brier_score_loss(y_test, y_pred_prob)
print(brier)

0.21077388943000427

In [ ]:
## Logistic Regression pipeline with balanced class weight (0.25024089874378147)

balanced_pipeline = Pipeline(steps=[
    ('preprocessor', preprocessor),
    ('classifier', LogisticRegression(class_weight='balanced', random_state=42))
])

balanced_pipeline.fit(X_train, y_train)

## Predict

balanced_y_pred_prob = balanced_pipeline.predict_proba(X_test)[:,1]

## Brier Score Loss
balanced_brier = brier_score_loss(y_test, balanced_y_pred_prob)
print(balanced_brier)

0.2502155330040003

In [ ]:
## Logistic Regression pipeline with higher weight to minority class (0.2500069097637534)

ratio_pipeline = Pipeline(steps=[
    ('preprocessor', preprocessor),
    ('classifier', LogisticRegression(class_weight={0: 0.29903, 1: 0.70097}, random_state=42))
])

ratio_pipeline.fit(X_train, y_train)

## Predict

ratio_y_pred_prob = ratio_pipeline.predict_proba(X_test)[:,1]

## Brier Score Loss
ratio_brier = brier_score_loss(y_test, ratio_y_pred_prob)
print(ratio_brier)

0.24999773383857993

In [10]:
## Hyperparameter Tuning

# param_grid = {
#     'preprocessor__num__imputer__n_neighbors': [3, 5, 7, 9, 11],
#     'classifier__C': [0.01, 0.1, 1, 10],
#     # 'classifier__solver': ['lbfgs', 'sag', 'saga'], 
#     'classifier__penalty': [None, 'l1', 'l2', 'elasticnet']
# }

param_grid = [
    {
        'preprocessor__num__imputer__n_neighbors': [3, 5, 7, 9, 11],
        'classifier__C': np.logspace(-3, 3, 5),
        'classifier__solver': ['newton-cholesky', 'lbfgs', 'sag'],
        'classifier__penalty': ['l2', None]
    },
    {
        'preprocessor__num__imputer__n_neighbors': [3, 5, 7, 9, 11],
        'classifier__C': np.logspace(-3, 3, 5),
        'classifier__solver': ['saga'],
        'classifier__penalty': ['l1', 'l2', None]
    },
    {
        'preprocessor__num__imputer__n_neighbors': [3, 5, 7, 9, 11],
        'classifier__C': np.logspace(-3, 3, 5),
        'classifier__solver': ['saga'],
        'classifier__penalty': ['elasticnet'],
        'classifier__l1_ratio': [0, 0.5, 1]
    }
]

In [11]:
## Set scoring function
brier_scorer = make_scorer(brier_score_loss, response_method='predict_proba', greater_is_better=False)

In [12]:
## Taking sample of data for gridsearch (20k points)
X_train_sample, X_test_sample, y_train_sample, y_test_sample = train_test_split(X, y, train_size = 0.2, test_size = 0.1, shuffle=True, stratify=y, random_state=42)

In [ ]:
## Extract sample data
# pd.concat([X_train_sample, y_train_sample]).to_csv('../Data/sampleData.csv', index=False)

In [ ]:
## KFold GridSearchCV (Parallel Computing)
## Training on full sample is too time consuming, using sample instead

cv = StratifiedKFold(n_splits = 5, shuffle=True, random_state=42)

grid_search = GridSearchCV(
    estimator = pipeline,    ## Default pipeline had lowest brier score loss
    param_grid = param_grid,
    scoring = brier_scorer,
    cv = cv,
    verbose = 2,
    n_jobs = -1
)

grid_search.fit(X_train_sample, y_train_sample) ## 80 min for 20% of data
# grid_search.fit(X_train, y_train)

Fitting 5 folds for each of 300 candidates, totalling 1500 fits

In [ ]:
## Best parameters: {'classifier__C': np.float64(0.001), 'classifier__l1_ratio': 0.5, 'classifier__penalty': 'elasticnet', 'classifier__solver': 'saga', 'preprocessor__num__imputer__n_neighbors': 9}
## Best Brier score: 0.2096192424560121

## Best parameters: {'classifier__C': np.float64(0.001), 'classifier__l1_ratio': 1, 'classifier__penalty': 'elasticnet', 'classifier__solver': 'saga', 'preprocessor__num__imputer__n_neighbors': 9}
## Best Brier score: 0.20961926537835912

print("Best parameters:", grid_search.best_params_)
print("Best Brier score:", -grid_search.best_score_)

Best parameters: {'classifier__C': np.float64(0.001), 'classifier__l1_ratio': 1, 'classifier__penalty': 'elasticnet', 'classifier__solver': 'saga', 'preprocessor__num__imputer__n_neighbors': 9}
Best Brier score: 0.20961926537835912

In [ ]:
params_df = pd.DataFrame(grid_search.cv_results_)
params_df.head()

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_classifier__C,param_classifier__penalty,param_classifier__solver,param_preprocessor__num__imputer__n_neighbors,param_classifier__l1_ratio,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,63.772460,1.071856,14.934812,0.586367,0.001,l2,newton-cholesky,3,NaN,"{'classifier__C': 0.001, 'classifier__penalty'...",-0.209784,-0.210261,-0.209852,-0.210106,-0.209913,-0.209983,0.000176,48
1,65.576087,1.592154,14.993097,0.974229,0.001,l2,newton-cholesky,5,NaN,"{'classifier__C': 0.001, 'classifier__penalty'...",-0.209790,-0.210250,-0.209856,-0.210106,-0.209908,-0.209982,0.000171,45
2,68.820398,2.935029,15.101425,1.286911,0.001,l2,newton-cholesky,7,NaN,"{'classifier__C': 0.001, 'classifier__penalty'...",-0.209786,-0.210252,-0.209865,-0.210082,-0.209891,-0.209975,0.000169,38
3,68.990604,1.120435,15.078294,0.833653,0.001,l2,newton-cholesky,9,NaN,"{'classifier__C': 0.001, 'classifier__penalty'...",-0.209779,-0.210253,-0.209855,-0.210083,-0.209886,-0.209971,0.000173,29
4,66.908555,3.323407,14.354343,1.031336,0.001,l2,newton-cholesky,11,NaN,"{'classifier__C': 0.001, 'classifier__penalty'...",-0.209779,-0.210255,-0.209867,-0.210087,-0.209878,-0.209973,0.000173,33

## Full Pipeline of all models to try

In [ ]:
models = {
    'Logistic Regression': Pipeline([
        ('preprocessor', preprocessor),
        ('model', LogisticRegression(random_state=42))
    ]),
    'Random Forest': Pipeline([
        ('preprocessor', preprocessor),
        ('model', RandomForestClassifier(random_state=42))
    ]),
    'Gradient Boosting': Pipeline([
        ('preprocessor', preprocessor),
        ('model', GradientBoostingClassifier(random_state=42))
    ]),
    'Decision Tree': Pipeline([
        ('preprocessor', preprocessor),
        ('model', DecisionTreeClassifier(random_state=42))
    ]),
    'KNN': Pipeline([
        ('preprocessor', preprocessor),
        ('model', KNeighborsClassifier(n_neighbors=5))
    ])
}

In [ ]:
## Train models and append results

results = []

for model, pipeline in tqdm(models.items(), desc="Training Models"):
    pipeline.fit(X_train_sample, y_train_sample)
    y_pred_prob = pipeline.predict_proba(X_test_sample)[:, 1]   ## class 1 is diseased
    
    brier = brier_score_loss(y_test_sample, y_pred_prob)
    logloss = log_loss(y_test_sample, y_pred_prob)
    
    results.append({
        'Model': model,
        'Brier Score Loss': brier,
        'Log Loss': logloss
    })

results_df = pd.DataFrame(results).sort_values(by='Log Loss')
results_df.to_csv('../Data/preliminaryResults.csv', index=False)
results_df

Training Models: 100%|██████████| 5/5 [01:33<00:00, 18.67s/it]

                 Model  Brier Score Loss   Log Loss
0  Logistic Regression          0.209844   0.610594
2    Gradient Boosting          0.210660   0.612515
1        Random Forest          0.212601   0.616953
4                  KNN          0.250232   2.357173
3        Decision Tree          0.423000  15.246465

In [ ]:
## Train models and append results (Full size)

results = []

for model, pipeline in tqdm(models.items(), desc="Training Models"):
    pipeline.fit(X_train, y_train)
    y_pred_prob = pipeline.predict_proba(X_test)[:, 1]   ## class 1 is diseased
    
    brier = brier_score_loss(y_test, y_pred_prob)
    logloss = log_loss(y_test, y_pred_prob)
    
    results.append({
        'Model': model,
        'Brier Score Loss': brier,
        'Log Loss': logloss
    })

results_df = pd.DataFrame(results).sort_values(by='Log Loss')
results_df.to_csv('../Data/preliminaryFullResults.csv', index=False)
results_df

Training Models: 100%|██████████| 5/5 [16:30<00:00, 198.05s/it]

                 Model  Brier Score Loss   Log Loss
2    Gradient Boosting          0.210741   0.612534
0  Logistic Regression          0.210774   0.612590
1        Random Forest          0.213722   0.619502
4                  KNN          0.251938   2.474187
3        Decision Tree          0.425300  15.329366

## Ensemble (Stacking Multiple Models and combining prediction)